[package]
name = "y2023-d8"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
common = { path = "../../common" }
nom = { workspace = true }
num = { workspace = true }
rustc-hash = { workspace = true }
