[package]
name = "y2022-d15"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
common = { path = "../../common" }
itertools = { workspace = true }
regex = { workspace = true }
