[package]
name = "y2024-d11"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
common = { path = "../../common" }
num = { workspace = true }
rustc-hash = { workspace = true }
