[package]
name = "y2022-d14"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
common = { path = "../../common" }
nom = { workspace = true }
rustc-hash = { workspace = true }
