[package]
name = "y2024-d24"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
common = { path = "../../common" }
rustc-hash = { workspace = true }
itertools = { workspace = true }
