[package]
name = "y2024-d22"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
common = { path = "../../common" }
rayon = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
parameterized = { workspace = true }
