[package]
name = "y2015-d11"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
common = { path = "../../common" }

[dev-dependencies]
parameterized = { workspace = true }
